# Generated by Django 3.2.14 on 2022-07-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('pupil', 'test', 'grade', 'score', 'date')},
        ),
    ]
