# Generated by Django 3.2.14 on 2022-07-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_exam_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupil',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='pupil',
            name='last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
